# Validation check:
# $ curl --data-binary @codecov.yaml https://codecov.io/validate

codecov:
  bot: "codecov-io"
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 1
  round: nearest
  range: 75...90
  status:
    project:
      default:
        informational: true
        target: 90%
        threshold: 1%
        if_ci_failed: error
        only_pulls: true
    patch:
      default:
        target: 85%

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

comment:
  layout: "reach,diff,flags,files,footer"
  require_changes: false
  behavior: default
