name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is and code snippets that will help us reproduce it.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Versions
    description: |
      Please provide the following info (and anything else you may find relevant)
      
      OS:
      Python:
      MongoDB:
      pymongo:
      VersionedCollection:
      
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
