name: Bump-Version Action
on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
  workflow_call:
    inputs:
      bump_type: # "major", "minor" or "patch"
        required: true
        type: string
jobs:

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Get current version
        id: get_current_version
        run: |
          IFS="=" read ignore version_number <<< $(sed -n '2p' VERSION)
          echo "version=${version_number//[[:space:]]/}" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: increment_version
        uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: ${{ steps.get_current_version.outputs.version }}
          version-fragment: ${{ inputs.bump_type }}

      - name: Update Version
        run: python3 .ci/update_version.py ${{ steps.increment_version.outputs.next-version }}


      - name: Commit Changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add VERSION versioned_collection/version.py
          message="[CI] Bumped Version to ${{ steps.increment_version.outputs.next-version }}"
          git commit -m "${message}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: ${{ github.ref }}

      - name: Checkout project 2
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Tag Version
        run: |
          tag=v${{ steps.increment_version.outputs.next-version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "${tag}"
          git push origin "${tag}"