name: versioned_collection Pull Request
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-pr
  cancel-in-progress: true

jobs:
  generate_tag:
    name: Generate version tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        id: tag
        uses: HumanisingAutonomy/versioned_collection/.github/actions/tag_version@main
        with:
          dry_run: "True"
    outputs:
      version: ${{steps.tag.outputs.version}}

  pr:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    name: versioned_collection PR
    runs-on: ubuntu-latest
    needs: generate_tag
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: Test, Build, Publish
        uses: HumanisingAutonomy/versioned_collection/.github/actions/test_and_build@main
        with:
          version: ${{ needs.generate_tag.outputs.version }}
          is_dev_run: "True"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          python_version: ${{ matrix.python_version }}
