name: versioned_collection Release
on:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-release
  cancel-in-progress: true

# TODO: matrix for all supported python versions
env:
  PYTHON_VERSION: "3.11"

jobs:
  generate_tag:
    name: Generate version tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        id: tag
        uses: HumanisingAutonomy/versioned_collection/.github/actions/tag_version@ci-refactor
        with:
          dry_run: "True"
    outputs:
      version: ${{steps.tag.outputs.version}}

  release:
    name: versioned_collection Release
    needs: generate_tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: Test, Build, Publish
        uses: HumanisingAutonomy/versioned_collection/.github/actions/test_and_build@ci-refactor
        with:
          version: ${{ needs.generate_tag.outputs.version }}
          is_dev_run: "False"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/build/html/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

  tag_repository:
    name: Tag repo with new version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Tag repo with new version
        uses: HumanisingAutonomy/versioned_collection/.github/actions/tag_version@ci-refactor
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}