name: versioned_collection Release
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-release
  cancel-in-progress: true


jobs:
  generate_tag:
    name: Generate version tag
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        id: tag
        uses: HumanisingAutonomy/versioned_collection/.github/actions/tag_version@main
        with:
          dry_run: "True"
    outputs:
      version: ${{steps.tag.outputs.version}}

  release:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
    name: versioned_collection Release
    needs: generate_tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
      pages: write
    steps:
      - name: Test, Build, Publish
        uses: HumanisingAutonomy/versioned_collection/.github/actions/test_and_build@main
        with:
          version: ${{ needs.generate_tag.outputs.version }}
          is_dev_run: "False"
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          python_version: ${{ matrix.python_version }}

  tag_repository:
    name: Tag repo with new version
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Tag repo with new version
        uses: HumanisingAutonomy/versioned_collection/.github/actions/tag_version@main
